### PR TITLE
fix: handle unzip exceptions

### LINKED ISSUE #162: Unhandled exception: `FileSystemException: readInto`
Hey there, I'm getting this error while trying to run your tool against my large (50GB) `tgz` takeout files. Please let me know if you need anything more from me regarding this error.

```bash
Unzipping takeout-20230122T143523Z-001.tgz...
Unhandled exception:
FileSystemException: readInto failed, path = '/var/folders/_c/z_r8csbn73j2dt50rsxg68hr0000gn/T/dart_archive9Hnqal/temp.tar' (OS Error: Invalid argument, errno = 22)
#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:799)
#1      FileHandle.readInto (package:archive/src/io/input_file_stream.dart:60)
#2      InputFileStream.toUint8List (package:archive/src/io/input_file_stream.dart:326)
#3      ArchiveFile.decompress (package:archive/src/archive_file.dart:169)
#4      ArchiveFile.content (package:archive/src/archive_file.dart:134)
#5      extractFileToDisk (package:archive/src/io/extract_archive_to_disk.dart:127)
<asynchronous suspension>
#6      unzip (package:gpth/interactive.dart:219)
<asynchronous suspension>
#7      main (file:///Users/runner/work/GooglePhotosTakeoutHelper/GooglePhotosTakeoutHelper/bin/gpth.dart:103)
<asynchronous suspension>
```

And is there anything that can be done about the speed of unpack these files? These 50GB `tgz`'s are taking _forever_!

Thanks!

### PR DESCRIPTION
**Pull request by matt-boris**
Fixes #162.

### CODE REVIEW

File: lib/interactive.dart [hunk 1]
```diff
@@ -216,6 +216,14 @@ Future<void> unzip(List<File> zips, Directory dir) async {
...
     print('Unzipping ${p.basename(zip.path)}...');
-    await extractFileToDisk(zip.path, dir.path, asyncWrite: true);
+    try {
+      await extractFileToDisk(zip.path, dir.path, asyncWrite: true);
+    } catch(e) {
+      error(
+        'Error occured while unzipping file.\n'
+        'Error details: ${e}',
+      )
+      exit(69);
```
Comment (TheLastGimbus) [inline lib/interactive.dart:226]: Using my own quit() func will work nicely with interactive :+1:
 
```suggestion
      quit(69);
```

File: lib/interactive.dart [hunk 2]
```diff
@@ -216,6 +216,14 @@ Future<void> unzip(List<File> zips, Directory dir) async {
...
   for (final zip in zips) {
     print('Unzipping ${p.basename(zip.path)}...');
-    await extractFileToDisk(zip.path, dir.path, asyncWrite: true);
+    try {
+      await extractFileToDisk(zip.path, dir.path, asyncWrite: true);
+    } catch(e) {
+      error(
+        'Error occured while unzipping file.\n'
+        'Error details: ${e}',
+      )
```
Comment (TheLastGimbus) [inline lib/interactive.dart:225]: Shorter :)
```suggestion
      error('Error while unzipping $zip :(\n$e);
```

**Review by TheLastGimbus — CHANGES_REQUESTED** [review]
Thanks! some edits but nice in general <3
